# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class UISetupForm(object):
    
   def setupUi(object,setupDialog):
       def gridBlock(inputDictionary):
           
           font = QtGui.QFont()
           font.setPointSize(26)
             #grid block layout
           grid = QtWidgets.QGridLayout()
           grid.setContentsMargins(0, 0, 0, 0)
           grid.setObjectName("grdSetup")
            
           headers = inputDictionary['headers']
            
           for i in range(len(headers)):
           
               grid.lbl = QtWidgets.QLabel()        
               grid.lbl.setFont(font)
               grid.lbl.setObjectName('lbl' + headers[i])
               grid.addWidget(grid.lbl, 0, i, 1, 1)
               grid.lbl.setText(headers[i])
           rowNames = inputDictionary['rowNames']
            
           for i in range(len(rowNames)):
               grid.lbl = QtWidgets.QLabel()        
               grid.lbl.setFont(font)
               grid.lbl.setObjectName('lbl' + rowNames[i])
               grid.addWidget(grid.lbl, i+1, 0, 1, 1)
               grid.lbl.setText(rowNames[i])  
                
                #get the row of widgets
               r = inputDictionary[rowNames[i]]
                #there will be a value for every column except the first one
               for h in headers[1:]:
                   grid.wid=getWidget(r[h]['widget'])
                   grid.wid.setFont(font)
                   grid.wid.setObjectName('inp'.join(r).join(h))
                   grid.addWidget(grid.wid,i+1,getColumn('lbl' + h,i,1,grid),1,1)
                   if 'items' in r[h].keys():
                       for item in r[h]['items']:
                           grid.wid.addItem(item)
                   print(getColumn('lbl' + h,i,1,grid))
           return grid
                
       def getColumn(objectName, row, c, gridLayout):
           o =gridLayout.itemAtPosition(0,c)
           if c > gridLayout.columnCount():
               return False
           if o is not None:
               o = o.widget()
               n = o.objectName()
               if n == objectName:
                   return c
           return getColumn(objectName,row,c+1,gridLayout)
       
       def getWidget(stringType):
           choices={'combo':QtWidgets.QComboBox()}
           result = choices.get(stringType,QtWidgets.QTextEdit())
           return result     
        
       setupDictGrid1 = {'headers':['Attribute','Field','Format'],
                          'rowNames':['Date','Time','Load'],
                          'Date':{'Field':{'widget':'combo','items':['Date','Time','Wtg1']},
                                           'Format':{'widget':'combo','items':['ordinal']}},
                          'Time':{'Field':{'widget':'combo','items':['Date','Time','Wtg1']},
                                           'Format':{'widget':'combo','items':['excel']}},
                          'Load':{'Field':{'widget':'combo','items':['Date','Wtg1']},
                                           'Format':{'widget':'combo','items':['KW','W','MW']}}
                          }
       setupDictGrid2 = {'headers':['TimeStep','Value','Units'],
                          'rowNames':['Input','Output'],
                          'Input':{'Value':{'widget':'txt'},
                                           'Units':{'widget':'combo','items':['Seconds','Minutes','Hours']}},
                          'Output':{'Value':{'widget':'txt'},
                                           'Units':{'widget':'combo','items':['Seconds','Minutes','Hours']}}
                          }
                          
        #overall form characteristics
       setupDialog.setObjectName("setupDialog")
       setupDialog.resize(1754, 1250)
       sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
       sizePolicy.setHorizontalStretch(0)
       sizePolicy.setVerticalStretch(0)
       sizePolicy.setHeightForWidth(setupDialog.sizePolicy().hasHeightForWidth())
       setupDialog.setSizePolicy(sizePolicy)
       layout = QtWidgets.QVBoxLayout()
#       self.layoutWidget = QtWidgets.QWidget(setupDialog)
#       self.layoutWidget.setGeometry(QtCore.QRect(800, 110, 874, 313))
#       self.layoutWidget.setObjectName("layoutWidget")
#       self.topgrid = QtWidgets.QGroupBox("topgroup")
#        #add the setup block
#       self.topgrid.setLayout(gridBlock(setupDictGrid1))
#       #grid = gridBlock(self.layoutWidget,setupDictGrid2)
#       
#       layout.addWidget(self.topgrid)
#       object.addWidget(layout)
       layoutWidget=QtWidgets.QWidget(setupDialog)
        #add the component block
        #componentBlock(self.layoutWidget)
        
#        #grid layout for date, time load field specifications
       
#            
#            self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_8.setEnabled(False)
#            self.comboBox_8.setFont(font)
#            self.comboBox_8.setObjectName("comboBox_8")
#            self.gridLayout_2.addWidget(self.comboBox_8, 2, 2, 1, 1)
#            
#            self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_9.setEnabled(False)
#            self.comboBox_9.setFont(font)
#            self.comboBox_9.setObjectName("comboBox_9")
#            self.gridLayout_2.addWidget(self.comboBox_9, 1, 2, 1, 1)
#            
#            self.label_9 = QtWidgets.QLabel(self.layoutWidget)
#            self.label_9.setFont(font)
#            self.label_9.setText("")
#            self.label_9.setObjectName("label_9")
#            self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
#            
#            self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_10.setEnabled(False)
#            self.comboBox_10.setFont(font)
#            self.comboBox_10.setObjectName("comboBox_10")
#            self.gridLayout_2.addWidget(self.comboBox_10, 3, 1, 1, 1)
#            
#            self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_11.setEnabled(False)
#            self.comboBox_11.setMinimumSize(QtCore.QSize(300, 0))
#            self.comboBox_11.setFont(font)
#            self.comboBox_11.setObjectName("comboBox_11")
#            self.gridLayout_2.addWidget(self.comboBox_11, 1, 1, 1, 1)
#            
#            self.label_10 = QtWidgets.QLabel(self.layoutWidget)
#            font = QtGui.QFont()
#            font.setPointSize(26)
#            self.label_10.setFont(font)
#            self.label_10.setObjectName("label_10")
#            self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
#            
#            self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_12.setEnabled(False)
#            self.comboBox_12.setFont(font)
#            self.comboBox_12.setObjectName("comboBox_12")
#            self.gridLayout_2.addWidget(self.comboBox_12, 2, 1, 1, 1)
#            
#            self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget)
#            self.comboBox_13.setEnabled(False)
#            self.comboBox_13.setFont(font)
#            self.comboBox_13.setObjectName("comboBox_13")
#            self.gridLayout_2.addWidget(self.comboBox_13, 3, 2, 1, 1)
#            
#            self.label_11 = QtWidgets.QLabel(self.layoutWidget)
#            self.label_11.setFont(font)
#            self.label_11.setObjectName("label_11")
#            self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
#            self.label_12 = QtWidgets.QLabel(self.layoutWidget)
#            
#            self.label_12.setFont(font)
#            self.label_12.setObjectName("label_12")
#            self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
#            self.label_13 = QtWidgets.QLabel(self.layoutWidget)
#            self.label_13.setFont(font)
#            self.label_13.setObjectName("label_13")
#            self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
#            
#        #components form
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.frmComponents = QtWidgets.QFrame(setupDialog)
#        self.frmComponents.setGeometry(QtCore.QRect(10, 460, 1721, 401))
#        self.frmComponents.setFrameShape(QtWidgets.QFrame.StyledPanel)
#        self.frmComponents.setFrameShadow(QtWidgets.QFrame.Raised)
#        self.frmComponents.setObjectName("frmComponents")
#        self.lblComponents = QtWidgets.QLabel(self.frmComponents)
#        self.lblComponents.setGeometry(QtCore.QRect(20, 10, 291, 41))
#       
#        self.lblComponents.setFont(font)
#        self.lblComponents.setObjectName("lblComponents")
#        self.widget = QtWidgets.QWidget(self.frmComponents)
#        self.widget.setGeometry(QtCore.QRect(0, 70, 1667, 253))
#        
#        self.widget.setFont(font)
#        self.widget.setObjectName("widget")
#        self.glayComponents = QtWidgets.QGridLayout(self.widget)
#        self.glayComponents.setContentsMargins(0, 0, 0, 0)
#        self.glayComponents.setObjectName("glayComponents")
#        self.rdoVoltageSource = QtWidgets.QRadioButton(self.widget)
#        
#        self.rdoVoltageSource.setFont(font)
#        self.rdoVoltageSource.setText("")
#        self.rdoVoltageSource.setIconSize(QtCore.QSize(30, 20))
#        self.rdoVoltageSource.setObjectName("rdoVoltageSource")
#        self.glayComponents.addWidget(self.rdoVoltageSource, 1, 13, 1, 2)
#        self.lblComponentNewName = QtWidgets.QLabel(self.widget)
#        
#        self.lblComponentNewName.setFont(font)
#        self.lblComponentNewName.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentNewName.setObjectName("lblComponentNewName")
#        self.glayComponents.addWidget(self.lblComponentNewName, 1, 6, 1, 1)
#        self.btnTags = QtWidgets.QToolButton(self.widget)
#        
#        self.btnTags.setFont(font)
#        self.btnTags.setObjectName("btnTags")
#        self.glayComponents.addWidget(self.btnTags, 1, 15, 1, 1)
#        self.toolButton_5 = QtWidgets.QToolButton(self.widget)
#        
#        self.toolButton_5.setFont(font)
#        self.toolButton_5.setObjectName("toolButton_5")
#        self.glayComponents.addWidget(self.toolButton_5, 2, 4, 1, 1)
#        self.label_17 = QtWidgets.QLabel(self.widget)
#        
#        self.label_17.setFont(font)
#        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
#        self.label_17.setObjectName("label_17")
#        self.glayComponents.addWidget(self.label_17, 2, 6, 1, 1)
#        self.lblComponentName = QtWidgets.QLabel(self.widget)
#        
#        self.lblComponentName.setFont(font)
#        self.lblComponentName.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentName.setObjectName("lblComponentName")
#        self.glayComponents.addWidget(self.lblComponentName, 0, 6, 1, 1)
#        self.lblVoltageSource = QtWidgets.QLabel(self.widget)
#       
#        self.lblVoltageSource.setFont(font)
#        self.lblVoltageSource.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblVoltageSource.setObjectName("lblVoltageSource")
#        self.glayComponents.addWidget(self.lblVoltageSource, 0, 13, 1, 1)
#        self.cmbComponentType = QtWidgets.QComboBox(self.widget)
#        
#        self.cmbComponentType.setFont(font)
#        self.cmbComponentType.setObjectName("cmbComponentType")
#        self.glayComponents.addWidget(self.cmbComponentType, 1, 5, 1, 1)
#        self.spnComponentOffset = QtWidgets.QDoubleSpinBox(self.widget)
#        
#        self.spnComponentOffset.setFont(font)
#        self.spnComponentOffset.setObjectName("spnComponentOffset")
#        self.glayComponents.addWidget(self.spnComponentOffset, 1, 8, 1, 1)
#        self.spnComponentScale = QtWidgets.QDoubleSpinBox(self.widget)
#       
#        self.spnComponentScale.setFont(font)
#        self.spnComponentScale.setObjectName("spnComponentScale")
#        self.glayComponents.addWidget(self.spnComponentScale, 1, 7, 1, 1)
#        self.btnDeleteComponent = QtWidgets.QToolButton(self.widget)
#        
#        self.btnDeleteComponent.setFont(font)
#        self.btnDeleteComponent.setObjectName("btnDeleteComponent")
#        self.glayComponents.addWidget(self.btnDeleteComponent, 1, 4, 1, 1)
#        self.cmbComponentAttribute = QtWidgets.QComboBox(self.widget)
#        
#        self.cmbComponentAttribute.setFont(font)
#        self.cmbComponentAttribute.setObjectName("cmbComponentAttribute")
#        self.cmbComponentAttribute.addItem("")
#        self.cmbComponentAttribute.addItem("")
#        self.cmbComponentAttribute.addItem("")
#        self.glayComponents.addWidget(self.cmbComponentAttribute, 1, 9, 1, 1)
#        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
#       
#        self.lineEdit_11.setFont(font)
#        self.lineEdit_11.setObjectName("lineEdit_11")
#        self.glayComponents.addWidget(self.lineEdit_11, 2, 0, 1, 2)
#        self.toolButton_6 = QtWidgets.QToolButton(self.widget)
#        
#        self.toolButton_6.setFont(font)
#        self.toolButton_6.setObjectName("toolButton_6")
#        self.glayComponents.addWidget(self.toolButton_6, 2, 2, 1, 2)
#        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.doubleSpinBox_3.setFont(font)
#        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
#        self.glayComponents.addWidget(self.doubleSpinBox_3, 2, 7, 1, 1)
#        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
#       
#        self.lineEdit_5.setFont(font)
#        self.lineEdit_5.setObjectName("lineEdit_5")
#        self.glayComponents.addWidget(self.lineEdit_5, 2, 10, 1, 1)
#        self.btnLoadDescriptor = QtWidgets.QToolButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.btnLoadDescriptor.setFont(font)
#        self.btnLoadDescriptor.setObjectName("btnLoadDescriptor")
#        self.glayComponents.addWidget(self.btnLoadDescriptor, 1, 2, 1, 2)
#        self.lblComponentAttribute = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblComponentAttribute.setFont(font)
#        self.lblComponentAttribute.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentAttribute.setObjectName("lblComponentAttribute")
#        self.glayComponents.addWidget(self.lblComponentAttribute, 0, 9, 1, 1)
#        self.txtPInMax = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.txtPInMax.setFont(font)
#        self.txtPInMax.setObjectName("txtPInMax")
#        self.glayComponents.addWidget(self.txtPInMax, 1, 10, 1, 1)
#        self.txtQIn = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.txtQIn.setFont(font)
#        self.txtQIn.setObjectName("txtQIn")
#        self.glayComponents.addWidget(self.txtQIn, 1, 11, 1, 1)
#        self.comboBox_15 = QtWidgets.QComboBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.comboBox_15.setFont(font)
#        self.comboBox_15.setObjectName("comboBox_15")
#        self.glayComponents.addWidget(self.comboBox_15, 2, 5, 1, 1)
#        self.lblComponentScale = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblComponentScale.setFont(font)
#        self.lblComponentScale.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentScale.setObjectName("lblComponentScale")
#        self.glayComponents.addWidget(self.lblComponentScale, 0, 7, 1, 1)
#        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.doubleSpinBox_4.setFont(font)
#        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
#        self.glayComponents.addWidget(self.doubleSpinBox_4, 2, 8, 1, 1)
#        self.comboBox_16 = QtWidgets.QComboBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.comboBox_16.setFont(font)
#        self.comboBox_16.setObjectName("comboBox_16")
#        self.glayComponents.addWidget(self.comboBox_16, 2, 9, 1, 1)
#        self.txtComponent = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.txtComponent.setFont(font)
#        self.txtComponent.setObjectName("txtComponent")
#        self.glayComponents.addWidget(self.txtComponent, 1, 0, 1, 2)
#        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_6.setFont(font)
#        self.lineEdit_6.setObjectName("lineEdit_6")
#        self.glayComponents.addWidget(self.lineEdit_6, 2, 11, 1, 1)
#        self.lblComponentOffset = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblComponentOffset.setFont(font)
#        self.lblComponentOffset.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentOffset.setObjectName("lblComponentOffset")
#        self.glayComponents.addWidget(self.lblComponentOffset, 0, 8, 1, 1)
#        self.lblPInMax = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblPInMax.setFont(font)
#        self.lblPInMax.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblPInMax.setObjectName("lblPInMax")
#        self.glayComponents.addWidget(self.lblPInMax, 0, 10, 1, 1)
#        self.lblQOut = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblQOut.setFont(font)
#        self.lblQOut.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblQOut.setObjectName("lblQOut")
#        self.glayComponents.addWidget(self.lblQOut, 0, 12, 1, 1)
#        self.lblTags = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblTags.setFont(font)
#        self.lblTags.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblTags.setObjectName("lblTags")
#        self.glayComponents.addWidget(self.lblTags, 0, 14, 1, 2)
#        self.lblQInMax = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblQInMax.setFont(font)
#        self.lblQInMax.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblQInMax.setObjectName("lblQInMax")
#        self.glayComponents.addWidget(self.lblQInMax, 0, 11, 1, 1)
#        self.txtQOut = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.txtQOut.setFont(font)
#        self.txtQOut.setObjectName("txtQOut")
#        self.glayComponents.addWidget(self.txtQOut, 1, 12, 1, 1)
#        self.toolButton_10 = QtWidgets.QToolButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.toolButton_10.setFont(font)
#        self.toolButton_10.setObjectName("toolButton_10")
#        self.glayComponents.addWidget(self.toolButton_10, 3, 15, 1, 1)
#        self.toolButton_7 = QtWidgets.QToolButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.toolButton_7.setFont(font)
#        self.toolButton_7.setObjectName("toolButton_7")
#        self.glayComponents.addWidget(self.toolButton_7, 2, 15, 1, 1)
#        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.radioButton_3.setFont(font)
#        self.radioButton_3.setText("")
#        self.radioButton_3.setObjectName("radioButton_3")
#        self.glayComponents.addWidget(self.radioButton_3, 3, 13, 1, 2)
#        self.toolButton_9 = QtWidgets.QToolButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.toolButton_9.setFont(font)
#        self.toolButton_9.setObjectName("toolButton_9")
#        self.glayComponents.addWidget(self.toolButton_9, 3, 2, 1, 2)
#        self.comboBox_17 = QtWidgets.QComboBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.comboBox_17.setFont(font)
#        self.comboBox_17.setObjectName("comboBox_17")
#        self.glayComponents.addWidget(self.comboBox_17, 3, 5, 1, 1)
#        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.doubleSpinBox_5.setFont(font)
#        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
#        self.glayComponents.addWidget(self.doubleSpinBox_5, 3, 8, 1, 1)
#        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_4.setFont(font)
#        self.lineEdit_4.setObjectName("lineEdit_4")
#        self.glayComponents.addWidget(self.lineEdit_4, 2, 12, 1, 1)
#        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_12.setFont(font)
#        self.lineEdit_12.setObjectName("lineEdit_12")
#        self.glayComponents.addWidget(self.lineEdit_12, 3, 0, 1, 2)
#        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_9.setFont(font)
#        self.lineEdit_9.setObjectName("lineEdit_9")
#        self.glayComponents.addWidget(self.lineEdit_9, 3, 10, 1, 1)
#        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.radioButton_2.setFont(font)
#        self.radioButton_2.setText("")
#        self.radioButton_2.setObjectName("radioButton_2")
#        self.glayComponents.addWidget(self.radioButton_2, 2, 13, 1, 2)
#        self.toolButton_8 = QtWidgets.QToolButton(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.toolButton_8.setFont(font)
#        self.toolButton_8.setObjectName("toolButton_8")
#        self.glayComponents.addWidget(self.toolButton_8, 3, 4, 1, 1)
#        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_8.setFont(font)
#        self.lineEdit_8.setObjectName("lineEdit_8")
#        self.glayComponents.addWidget(self.lineEdit_8, 3, 12, 1, 1)
#        self.comboBox_18 = QtWidgets.QComboBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.comboBox_18.setFont(font)
#        self.comboBox_18.setObjectName("comboBox_18")
#        self.glayComponents.addWidget(self.comboBox_18, 3, 9, 1, 1)
#        self.label_19 = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.label_19.setFont(font)
#        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
#        self.label_19.setObjectName("label_19")
#        self.glayComponents.addWidget(self.label_19, 3, 6, 1, 1)
#        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.doubleSpinBox_6.setFont(font)
#        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
#        self.glayComponents.addWidget(self.doubleSpinBox_6, 3, 7, 1, 1)
#        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lineEdit_7.setFont(font)
#        self.lineEdit_7.setObjectName("lineEdit_7")
#        self.glayComponents.addWidget(self.lineEdit_7, 3, 11, 1, 1)
#        self.lblComponentType = QtWidgets.QLabel(self.widget)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblComponentType.setFont(font)
#        self.lblComponentType.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblComponentType.setObjectName("lblComponentType")
#        self.glayComponents.addWidget(self.lblComponentType, 0, 5, 1, 1)
#        self.lblHeader = QtWidgets.QLabel(self.widget)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#        sizePolicy.setHorizontalStretch(1)
#        sizePolicy.setVerticalStretch(1)
#        sizePolicy.setHeightForWidth(self.lblHeader.sizePolicy().hasHeightForWidth())
#        self.lblHeader.setSizePolicy(sizePolicy)
#        font = QtGui.QFont()
#        font.setPointSize(20)
#        self.lblHeader.setFont(font)
#        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
#        self.lblHeader.setObjectName("lblHeader")
#        self.glayComponents.addWidget(self.lblHeader, 0, 0, 1, 2)
#        self.widget1 = QtWidgets.QWidget(setupDialog)
#        self.widget1.setGeometry(QtCore.QRect(10, 110, 681, 313))
#        self.widget1.setObjectName("widget1")
#        self.grdDateTime = QtWidgets.QGridLayout(self.widget1)
#        self.grdDateTime.setContentsMargins(0, 0, 0, 0)
#        self.grdDateTime.setObjectName("grdDateTime")
#        self.lblDate = QtWidgets.QLabel(self.widget1)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.lblDate.setFont(font)
#        self.lblDate.setObjectName("lblDate")
#        self.grdDateTime.addWidget(self.lblDate, 1, 0, 1, 1)
#        self.cmbTimeType = QtWidgets.QComboBox(self.widget1)
#        self.cmbTimeType.setEnabled(False)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.cmbTimeType.setFont(font)
#        self.cmbTimeType.setObjectName("cmbTimeType")
#        self.grdDateTime.addWidget(self.cmbTimeType, 2, 2, 1, 1)
#        self.cmbDateType = QtWidgets.QComboBox(self.widget1)
#        self.cmbDateType.setEnabled(False)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.cmbDateType.setFont(font)
#        self.cmbDateType.setObjectName("cmbDateType")
#        self.grdDateTime.addWidget(self.cmbDateType, 1, 2, 1, 1)
#        self.lblLoad = QtWidgets.QLabel(self.widget1)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.lblLoad.setFont(font)
#        self.lblLoad.setObjectName("lblLoad")
#        self.grdDateTime.addWidget(self.lblLoad, 3, 0, 1, 1)
#        self.cmbLoadField = QtWidgets.QComboBox(self.widget1)
#        self.cmbLoadField.setEnabled(False)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.cmbLoadField.setFont(font)
#        self.cmbLoadField.setObjectName("cmbLoadField")
#        self.grdDateTime.addWidget(self.cmbLoadField, 3, 1, 1, 1)
#        self.cmbDateField = QtWidgets.QComboBox(self.widget1)
#        self.cmbDateField.setEnabled(False)
#        self.cmbDateField.setMinimumSize(QtCore.QSize(300, 0))
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.cmbDateField.setFont(font)
#        self.cmbDateField.setObjectName("cmbDateField")
#        self.grdDateTime.addWidget(self.cmbDateField, 1, 1, 1, 1)
#        self.lblTime = QtWidgets.QLabel(self.widget1)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.lblTime.setFont(font)
#        self.lblTime.setObjectName("lblTime")
#        self.grdDateTime.addWidget(self.lblTime, 2, 0, 1, 1)
#        self.cmbTimeField = QtWidgets.QComboBox(self.widget1)
#        self.cmbTimeField.setEnabled(False)
#        font = QtGui.QFont()
#        font.setPointSize(26)
#        self.cmbTimeField.setFont(font)
#        self.cmbTimeField.setObjectName("cmbTimeField")
#        self.grdDateTime.addWidget(self.cmbTimeField, 2, 1, 1, 1)
#        self.cmbLoadUnits = QtWidgets.QComboBox(self.widget1)
#        self.cmbLoadUnits.setEnabled(False)
#       
#        self.cmbLoadUnits.setFont(font)
#        self.cmbLoadUnits.setObjectName("cmbLoadUnits")
#        self.grdDateTime.addWidget(self.cmbLoadUnits, 3, 2, 1, 1)
#        self.lblField = QtWidgets.QLabel(self.widget1)
#       
#        self.lblField.setFont(font)
#        self.lblField.setObjectName("lblField")
#        self.grdDateTime.addWidget(self.lblField, 0, 0, 1, 1)
#        self.lblColumn = QtWidgets.QLabel(self.widget1)
#        
#        self.lblColumn.setFont(font)
#        self.lblColumn.setObjectName("lblColumn")
#        self.grdDateTime.addWidget(self.lblColumn, 0, 1, 1, 1)
#        self.lblUnits = QtWidgets.QLabel(self.widget1)
#        
#        self.lblUnits.setFont(font)
#        self.lblUnits.setObjectName("lblUnits")
#        self.grdDateTime.addWidget(self.lblUnits, 0, 2, 1, 1)
#        self.widget2 = QtWidgets.QWidget(setupDialog)
#        self.widget2.setGeometry(QtCore.QRect(10, 30, 881, 42))
#        self.widget2.setObjectName("widget2")
#        
#        #project info
#        self.hlayProject = QtWidgets.QHBoxLayout(self.widget2)
#        self.hlayProject.setContentsMargins(0, 0, 0, 0)
#        self.hlayProject.setObjectName("hlayProject")
#        self.lblProjectName = QtWidgets.QLabel(self.widget2)
#        self.lblProjectName.setMinimumSize(QtCore.QSize(300, 40))
#        self.lblProjectName.setMaximumSize(QtCore.QSize(300, 30))
#       
#        self.lblProjectName.setFont(font)
#        self.lblProjectName.setObjectName("lblProjectName")
#        self.hlayProject.addWidget(self.lblProjectName)
#        self.txtProjectName = QtWidgets.QTextEdit(self.widget2)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.txtProjectName.sizePolicy().hasHeightForWidth())
#        self.txtProjectName.setSizePolicy(sizePolicy)
#        self.txtProjectName.setMinimumSize(QtCore.QSize(300, 40))
#        self.txtProjectName.setMaximumSize(QtCore.QSize(500, 30))
#        self.txtProjectName.setToolTip("")
#        self.txtProjectName.setObjectName("txtProjectName")
#        self.hlayProject.addWidget(self.txtProjectName)
#        self.btnData = QtWidgets.QToolButton(self.widget2)
#       
#        self.btnData.setFont(font)
#        self.btnData.setObjectName("btnData")
#        self.hlayProject.addWidget(self.btnData)
#        self.btnSetup = QtWidgets.QPushButton(self.widget2)
#        
#        self.btnSetup.setFont(font)
#        self.btnSetup.setObjectName("btnSetup")
#        self.hlayProject.addWidget(self.btnSetup)
#        
    

       #retranslateUi(setupDialog)
       QtCore.QMetaObject.connectSlotsByName(setupDialog)
       return setupDialog
   def retranslateUi(self, setupDialog):
        _translate = QtCore.QCoreApplication.translate
        setupDialog.setWindowTitle(_translate("setupDialog", "Dialog"))
#        self.lblInputInterval.setText(_translate("setupDialog", "Input:"))
#        self.lblOutputInterval.setText(_translate("setupDialog", "Output:"))
#        self.lblTimeInterval.setText(_translate("setupDialog", "Time Interval"))
#        self.lblTimeValues.setText(_translate("setupDialog", "<html><head/><body><p align=\"center\">Value</p></body></html>"))
#        self.lblTimeUnits.setText(_translate("setupDialog", "<html><head/><body><p align=\"center\">Units</p></body></html>"))
#        self.lblComponents.setText(_translate("setupDialog", "Components"))
#        self.lblComponentNewName.setText(_translate("setupDialog", "wtg1P"))
#        self.btnTags.setText(_translate("setupDialog", "..."))
#        self.btnUploadComponent.setText(_translate("setupDialog", "..."))
#        self.rowComponentName.setText(_translate("setupDialog", "="))
#        self.lblComponentName.setText(_translate("setupDialog", "Name"))
#        self.lblVoltageSource.setText(_translate("setupDialog", "<html><head/><body><p>Voltage <br/>Source?</p></body></html>"))
#        self.btnDeleteComponent.setText(_translate("setupDialog", "..."))
#        self.cmbComponentAttribute.setItemText(0, _translate("setupDialog", "P"))
#        self.cmbComponentAttribute.setItemText(1, _translate("setupDialog", "WS"))
#        self.cmbComponentAttribute.setItemText(2, _translate("setupDialog", "HS"))
#        
#        self.btnLoadDescriptor.setText(_translate("setupDialog", "..."))
#        self.lblComponentAttribute.setText(_translate("setupDialog", "Attribute"))
#        self.lblComponentScale.setText(_translate("setupDialog", "Scale"))
#        self.lblComponentOffset.setText(_translate("setupDialog", "Offset"))
#        self.lblPInMax.setText(_translate("setupDialog", "P In\n"
#" Max Pa"))
#        self.lblQOut.setText(_translate("setupDialog", "Q Out \n"
#"Max Pa"))
#        self.lblTags.setText(_translate("setupDialog", "Tags"))
#        self.lblQInMax.setText(_translate("setupDialog", "<html><head/><body><p>Q In </p><p>Max Pa</p></body></html>"))
#
#        
#        self.lblComponentType.setText(_translate("setupDialog", "Type"))
#        self.lblHeader.setText(_translate("setupDialog", "Component"))
#        self.lblDate.setText(_translate("setupDialog", "Date:"))
#        self.lblLoad.setText(_translate("setupDialog", "Load:"))
#        self.lblTime.setText(_translate("setupDialog", "Time:"))
#        self.lblField.setText(_translate("setupDialog", "Field"))
#        self.lblColumn.setText(_translate("setupDialog", "<html><head/><body><p align=\"center\">Column</p></body></html>"))
#        self.lblUnits.setText(_translate("setupDialog", "<html><head/><body><p align=\"center\">Units</p></body></html>"))
#        self.lblProjectName.setText(_translate("setupDialog", "Project Name:"))
#        self.btnData.setText(_translate("setupDialog", "Load Data"))
#        self.btnSetup.setText(_translate("setupDialog", "Load Setup xml"))
#
